#!/bin/bash -x

set -e

REPO_ROOT=$(git rev-parse --show-toplevel)
COMMIT=$(git rev-parse HEAD)
BRANCH=$(git rev-parse --abbrev-ref HEAD)
cd $REPO_ROOT
./_scripts/build

WORKDIR=$(mktemp -d)
function cleanup {
	[ -z "$WORKDIR" ] || rm -rf "$WORKDIR"
}
trap cleanup EXIT

[ -z "$WORKDIR" ] && exit 1

cd "$WORKDIR"
export GIT_DIR=$REPO_ROOT/.git
git checkout master || git checkout --orphan master
rm -rf $WORKDIR/*
tar xzf $REPO_ROOT/site.tar.gz
git add .
git commit -m "Build $BRANCH" -m "Built from $COMMIT"
rm -rf *
git checkout $BRANCH
cd $REPO_ROOT
