#!/bin/bash

[ -z "${IMAGE}" ] && IMAGE="merovius/jekyll:$(date +'%Y-%m')-$(./scripts/ha.sh)"
echo "Using ${IMAGE}"

OUT=$(mktemp -d)
[ -z "$OUT" ] && exit 1

function cleanup {
	rm -rf "$OUT"
}
trap cleanup EXIT

sudo docker run -i -t \
				--read-only \
				-v `pwd`:/src:ro,Z \
				--tmpfs /tmp \
				-v $OUT:/tmp/out:Z \
				-w /src/jekyll \
				${IMAGE} \
				/bin/bash -c "jekyll build --destination /tmp/_site && tar czf /tmp/out/site.tar.gz -C /tmp/_site ."
mv $OUT/site.tar.gz .
