#!/bin/bash

[ -z "${IMAGE}" ] && IMAGE="merovius/jekyll:$(date +'%Y-%m')-$(./scripts/ha.sh)"
echo "Using ${IMAGE}"

exec sudo docker run -i -t \
				-v `pwd`:/src:ro,Z \
				--tmpfs /tmp \
				-p 4000:4000 \
				${IMAGE} \
				/bin/bash
