#!/bin/bash

[ -z "${IMAGE}" ] && IMAGE="merovius/jekyll:$(date +'%Y-%m')-$(./scripts/ha.sh)"
echo "Using ${IMAGE}"

exec sudo docker run -i -t \
				--read-only \
				-v `pwd`:/src:ro,Z \
				--tmpfs /tmp \
				-p 4000:4000 \
				-w /src/jekyll \
				${IMAGE} \
				jekyll serve --destination /tmp/_site --watch --drafts
